### ISSUE TITLE
What happens to `value_and_gradient!!` if the output is not a `Float64`?

### ISSUE THREAD

**Issue by gdalle** [withbayes/Tapir.jl#116]
https://github.com/withbayes/Tapir.jl/blob/f5e2b90cd17fd3127dd0fd8dfa617bc112275626/src/interface.jl#L17-L24

**Comment by gdalle** [comment]
Wouldn't it be possible to grab the type `T` of the output, assuming it's a scalar type, and use `one(T)` as the pullback seed`

**Comment by willtebbutt** [comment]
Provided you also constrain it to a known collection of "real-valued" types (`Float16`, `Float32`, `BigFloat`, etc), I agree that should work.

I'm not really testing on anything other than `Float64` at the minute for the sake of expedience though, which is why I've gone with `1.0`. When I widen the range of types that I'm confident we have decent support for, I'll widen the permissible types.

**Comment by gdalle** [comment]
Sounds good! I was mostly curious

**Comment by willtebbutt** [comment]
Cool. Please feel free to re-open if there's anything else to chat about on this point :)
